#!/bin/bash
# set -euo pipefail
set -x
URL=${URL:-https://google.com}
export USR=${USR:=admin}
export PASS=${PASS:=root}
echo "$USR:$PASS" | chpasswd
rm -rf /tmp/*
DB_PID=$!
Xorg &
X_PID=$!
echo "Waiting for X to be ready"
export DISPLAY=:0
# Setting wallpaper and polling X in one!
while ! feh --bg-scale /etc/wallpaper.png; do sleep 1; done
matchbox-window-manager -use_cursor no &
while ! curl -sf -o /dev/null "$URL"; do sleep 1; done
xset -dpms
xset s off
xset s noblank
iceweasel "$URL"
sleep infinity
