#!/bin/bash
# set -euo pipefail
set -x
PATH=${PATH}
export USR=${USR:=admin}
export PASS=${PASS:=root}
DISPLAY_URL= "https://$USR:$PASS@grafana.tools.ygrene.com"
rm -rf /tmp/*
DB_PID=$!
Xorg &
X_PID=$!
echo "Waiting for X to be ready"
export DISPLAY=:0
# Setting wallpaper and polling X in one!
matchbox-window-manager -use_cursor no &
while ! curl -sf -o /dev/null "$DISPLAY_URL"; do sleep 1; done
xset -dpms
xset s off
xset s noblank
iceweasel "$URL"
sleep infinity
